### ISSUE TITLE
Cannot upload more than 1 image until refresh the workspace

### ISSUE THREAD

**Issue by zhlnhn** [Ben-Wolf/IBEIS-web#3]
Uploading images doesn't work after upload 1 image

**Comment by Ben-Wolf** [comment]
After you attempt to upload the buttons lock.

**Comment by Ben-Wolf** [comment]
Resolved in https://github.com/Ben-Wolf/IBEIS-web/commit/f0d6573de83b5af39ff0a51e517f30c915d869c3
