### ISSUE TITLE
Center loading wheel for workspace loading

### ISSUE THREAD

**Issue by Ben-Wolf** [Ben-Wolf/IBEIS-web#35]
The loading wheel awkwardly exists at the top, right under the workspace bar, center it, or find a more natural position for it.

**Comment by Ethan-Gibs** [comment]
So, I think I have a fix, but I'm not sure if I went about it in the right way? I added some padding in angular-material.css to ".layout-align-space-around-center" and it's centered, but I was wondering if there's a better way to go about that.

**Comment by Ben-Wolf** [comment]
You definitely want to modify the CSS, but I'm not sure adding padding is the best way to do it (though it might be). Does it stay centered when you resize, etc. Try running detection (it won't load), but is that loading sequence centered as well.

This thread seems like a good resource: https://stackoverflow.com/questions/24961121/how-to-display-loading-gif-at-the-center-of-the-screen-which-has-a-scrollbar

**Comment by Ethan-Gibs** [comment]
Ok, I think I got it right this time. I changed it to use the flex container then just used the "align-items: center;" "justify-content: center;"
I made sure to include the other stuff that's used every other time a flex container is used. I think its for other browsers, but I'm not sure.

**Comment by Ben-Wolf** [comment]
Awesome, feel free to make a PR with the changes now 👍 you can also merge if youre confident in it, if not I'll take a look at it tomorrow.
