### ISSUE TITLE
Workspace data not loading in

### ISSUE THREAD

**Issue by Ben-Wolf** [Ben-Wolf/IBEIS-web#38]
Make sure the workspace data can be loaded in, currently not working and only working for 'Drop Zone Test'

**Comment by Ben-Wolf** [comment]
Workspaces do load in after server was reset, if we encounter this type of error again either force delete a workspace (change code to delete a specific workspace on load in) or ask Jon V to reset the server.

**Comment by naknomum** [comment]
i need to have a better way to let everyone know when i am messing with the server!  for now, i will plan on shouting out to **#wildbook on rcos.slack** ....   also: i think i really need to start a second dev server for myself, so when i am doing _substantial_ changes, i am not doing it on the instance you all are using!  (e.g. i am doing that now trying to implement the backend for the v2 **identity graph** IA stuff)
