### ISSUE TITLE
Fix Select Images

### ISSUE THREAD

**Issue by Ethan-Gibs** [Ben-Wolf/IBEIS-web#41]
Currently images can be selected by dragging and dropping them into the workspace. However, using the "Select Images" button in the window that pops up doesn't currently work.

**Comment by Ben-Wolf** [comment]
Added a temporary fix for this. The problem seems to be in calling the "upload-img-btn" through the proxy. it worked before, and the actual functionality works when not called through the proxy.

**Comment by Ben-Wolf** [comment]
Gonna close this for now. technically fixed, just ugly rn
