### ISSUE TITLE
Implement the dummy detection and identification calls

### ISSUE THREAD

**Issue by Ben-Wolf** [Ben-Wolf/IBEIS-web#51]
The calls wont work yet, but they should all be put into the appropriate places.

**Comment by naknomum** [comment]
i am working on getting _something_ going on the backend for this.  in theory, the detection part should be "working".  theory and practice are proving to be two different things (see: software).  will keep you posted.  (but in the meantime, assume the calls i mention in the wb ia api google doc will be functional.)
